
package Vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;


public class MenuPrincipal extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;
    
    public MenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu prontomueble");
        
       this.setLayout(null);
       jDesktopPane_menu= new JDesktopPane();
       
       int ancho=java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
       int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
       this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto-110));
       this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu_Mueble_nuevo = new javax.swing.JMenu();
        jMenu_agrerarMueble = new javax.swing.JMenuItem();
        jMenu_verMueble = new javax.swing.JMenuItem();
        jMenu_ActualizarMueble = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Proveedor");
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 50));
        jMenuBar1.add(jMenu1);

        jMenu_Mueble_nuevo.setText("Mueble");
        jMenu_Mueble_nuevo.setPreferredSize(new java.awt.Dimension(100, 50));

        jMenu_agrerarMueble.setText("Agregar mueble");
        jMenu_agrerarMueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_agrerarMuebleActionPerformed(evt);
            }
        });
        jMenu_Mueble_nuevo.add(jMenu_agrerarMueble);

        jMenu_verMueble.setText("Ver mueble");
        jMenu_Mueble_nuevo.add(jMenu_verMueble);

        jMenu_ActualizarMueble.setText("Agregar stock");
        jMenu_ActualizarMueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ActualizarMuebleActionPerformed(evt);
            }
        });
        jMenu_Mueble_nuevo.add(jMenu_ActualizarMueble);

        jMenuBar1.add(jMenu_Mueble_nuevo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_agrerarMuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_agrerarMuebleActionPerformed
        Agregar_mueble Agregar_mueble= new Agregar_mueble();
        jDesktopPane_menu.add(Agregar_mueble);
        Agregar_mueble.setVisible(true);
    }//GEN-LAST:event_jMenu_agrerarMuebleActionPerformed

    private void jMenu_ActualizarMuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ActualizarMuebleActionPerformed
         ActualizarMueble ActualizarMueble= new ActualizarMueble();
        jDesktopPane_menu.add(ActualizarMueble);
        ActualizarMueble.setVisible(true); 
    }//GEN-LAST:event_jMenu_ActualizarMuebleActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenu_ActualizarMueble;
    private javax.swing.JMenu jMenu_Mueble_nuevo;
    private javax.swing.JMenuItem jMenu_agrerarMueble;
    private javax.swing.JMenuItem jMenu_verMueble;
    // End of variables declaration//GEN-END:variables
}
